import { knowledgeArticleList, knowledgeOverview } from "@/lib/knowledge/knowledgeArticles";
import { productGallery } from '@/lib/products/gallery';
import type { ShopifyProduct } from '@/lib/shopify/product-types';
import { absoluteUrl } from './site';

// Google permits at most 1,000 images per page. Keep the original source URL,
// rather than indexing every size generated by the Next.js image optimizer.
export function sitemapImages(sources: readonly string[]): string[] {
  return [...new Set(sources.map(absoluteUrl))].slice(0, 1000);
}

export function productSitemapImages(product: ShopifyProduct): string[] {
  return sitemapImages(product.variants.nodes.flatMap((variant) => {
    const gallery = productGallery(product, variant);
    return [...gallery.desktop, ...gallery.mobile].map((image) => image.url);
  }));
}

// Content images actually displayed by these pages. Decorative icons/logos and
// metadata-only Open Graph images are deliberately omitted.
export const editorialSitemapImages: Readonly<Record<string, readonly string[]>> = {
  '/': [
    '/JUSTER.png',
    '/JUSTER_1440x1800.png',
    '/images/promise/techdown-kate-kikkert-1080.webp',
    '/images/promise/kaffe-med-tilpasset-utekos-mikrofiber-vinter-terrasse-.webp',
    '/images/promise/techdown-monica-1080.webp',
    '/images/promise/techdown-kristoffer-1080.webp',
  ],
  '/om-oss': [
    '/om-oss.webp',
    '/UtekosGrunder.webp',
    '/messe-1.webp', '/messe-2.webp', '/messe-3.webp', '/messe-4.webp',
    '/glimt-1.webp', '/glimt-2.webp', '/glimt-3.webp',
    '/glimt-4.webp', '/glimt-5.webp', '/glimt-6.webp',
  ],
  [knowledgeOverview.path]: knowledgeArticleList.map(article => article.cardImage.src),
  ...Object.fromEntries(knowledgeArticleList.map(article => [article.path, article.images.map(image => image.src)])),
};
